package org.item.web.webclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2018-01-05T11:16:29.991+08:00
 * Generated source version: 3.1.14
 * 
 */
@WebService(targetNamespace = "http://webservice.web.item.org/", name = "WebRequestService")
@XmlSeeAlso({ObjectFactory.class})
public interface WebRequestService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "save", targetNamespace = "http://webservice.web.item.org/", className = "org.item.web.webclient.Save")
    @WebMethod
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://webservice.web.item.org/", className = "org.item.web.webclient.SaveResponse")
    public int save(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryUser", targetNamespace = "http://webservice.web.item.org/", className = "org.item.web.webclient.QueryUser")
    @WebMethod
    @ResponseWrapper(localName = "queryUserResponse", targetNamespace = "http://webservice.web.item.org/", className = "org.item.web.webclient.QueryUserResponse")
    public java.util.List<org.item.web.webclient.WxUser> queryUser();
}
