package org.item.web.webclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2018-01-05T11:16:30+08:00
 * Generated source version: 3.1.14
 * 
 */
@WebServiceClient(name = "WebRequestServiceImplService", 
                  wsdlLocation = "http://localhost:8081/web/webservice/userService?wsdl",
                  targetNamespace = "http://webservice.web.item.org/") 
public class WebRequestServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.web.item.org/", "WebRequestServiceImplService");
    public final static QName WebRequestServiceImplPort = new QName("http://webservice.web.item.org/", "WebRequestServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/web/webservice/userService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebRequestServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/web/webservice/userService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WebRequestServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebRequestServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebRequestServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WebRequestServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WebRequestServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WebRequestServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WebRequestService
     */
    @WebEndpoint(name = "WebRequestServiceImplPort")
    public WebRequestService getWebRequestServiceImplPort() {
        return super.getPort(WebRequestServiceImplPort, WebRequestService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebRequestService
     */
    @WebEndpoint(name = "WebRequestServiceImplPort")
    public WebRequestService getWebRequestServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WebRequestServiceImplPort, WebRequestService.class, features);
    }

}
